POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
  "username": "opboi",
  "email": "opboi@gmail.com",
  "password": "aa"
}

###
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
  "email": "opboi@gmail.com",
  "password": "aa"
}

###
POST http://localhost:5000/api/notes
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjUsImlhdCI6MTc1OTE1Mzg4MiwiZXhwIjoxNzU5MTU3NDgyfQ._OAXG3_sUX4Zqh8klOfO-QA5SnPOkhbDfCowxPZQjfA

{
  "title": "My secure note",
  "content": "This note is created with authentication."
}

### 
PUT http://localhost:5000/api/notes/4
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjYsImlhdCI6MTc1OTI0MzAzNSwiZXhwIjoxNzU5MjQ2NjM1fQ.UPdoT4RtzeBIqDSpTy5N7I24lWvuyQV2_ozga3BrXAM
Content-Type: application/json

{
  "title": "Updated Note Title",
  "content": "Updated content for the note."
}

###
DELETE http://localhost:5000/api/notes/4
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjYsImlhdCI6MTc1OTI0MzAzNSwiZXhwIjoxNzU5MjQ2NjM1fQ.UPdoT4RtzeBIqDSpTy5N7I24lWvuyQV2_ozga3BrXAM
